### ISSUE TITLE
Async.Resolved doesn't render if data is undefined

### ISSUE THREAD

**Issue by jlai** [ghengeveld/react-async#18] opened 2019-01-29 01:27 UTC
If your promiseFn resolves with an undefined value (e.g. `async () => {}`), the `Async.Resolved` helper doesn't render because it's checking for `state.data !== undefined` rather than whether the promise resolved or not.

For example

```js
<Async promiseFn={async () => {}}>
  {({ isLoading, data, error }) => !(isLoading || error) && `Success: data is ${data}`}
</Async>
```

will render "Success: data is undefined" while the following

```js
<Async promiseFn={async () => {}}>
  <Async.Resolved>({ data }) => `Success: data is ${data}`</Async.Resolved>
</Async>
```

will not render anything. Since it's named `Async.Resolved`, I would expect it to render regardless of the value of `data`.

**Comment by ghengeveld** [comment] 2019-01-29 06:48
Good observation, thanks for reporting! I never considered you would ever want to resolve without a value (you can always return `null` instead). I'll investigate a fix.

**Comment by ghengeveld** [comment] 2019-02-12 12:33
Considering there's an easy workaround, and not a simple solution, I'm going to close this as "works as intended" and add some clarification to the docs.

**Closed** 2019-02-12 12:34 UTC
